//
//  DetailEquipmentScreenViewController.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "DetailEquipmentScreenViewController.h"

#import "GradientView.h"
#import "MKMapView+ZoomLevel.h"

@implementation DetailEquipmentScreenViewController


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return UIInterfaceOrientationIsLandscape(toInterfaceOrientation);
}


- (void)viewDidLoad {
  [super viewDidLoad];
  
  // ----------------------------;
  // View Controller Root View;
  // ----------------------------;
  
  UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 1024, 748)];
  contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  
  // ----------------------------;
  // UINavigationBar -> navigationBar1;
  // ----------------------------;
  
  UINavigationBar *navigationBar1 = [[UINavigationBar alloc] initWithFrame:CGRectMake(0, 0, 1024, 44)];
  navigationBar1.delegate = (id<UINavigationBarDelegate>)self;
  UINavigationItem *navigationBar1BackItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  UINavigationItem *navigationBar1TopItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  NSArray *navigationBar1Items = [NSArray arrayWithObjects:navigationBar1BackItem, navigationBar1TopItem, nil];
  [navigationBar1 setItems:navigationBar1Items animated:NO];
  [contentView addSubview:navigationBar1];
  navigationBar1.alpha = 1.0;
  navigationBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
  navigationBar1.barStyle = UIBarStyleDefault;
  navigationBar1.tintColor = [UIColor colorWithRed:0.2 green:0.2 blue:0.2 alpha:1.0];
  navigationBar1.topItem.title = @"Net Zero Live";
  [navigationBar1 setTitleVerticalPositionAdjustment:0.0 forBarMetrics:UIBarMetricsDefault];
  navigationBar1.topItem.hidesBackButton = YES;
  
  // ----------------------------;
  // Navigation Bar Right Button -> barButton1;
  // ----------------------------;
  
  UIBarButtonItem *barButton1 = [[[UIBarButtonItem alloc] initWithTitle:@"Close" style:UIBarButtonItemStyleBordered target:nil action:nil] autorelease];
  barButton1.target = self;
  barButton1.action = @selector(didTap_barButton1:forEvent:);
  
  navigationBar1.topItem.rightBarButtonItem = barButton1;
  [navigationBar1 release];
  
  
  // ----------------------------;
  // MockTextureView -> textureView1;
  // ----------------------------;
  
  UIView *textureView1 = [[UIView alloc] initWithFrame:CGRectMake(20, 65, 500, 540)];
  UIView *textureView1ContentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 500, 540)];
  textureView1ContentView.clipsToBounds = YES;
  textureView1ContentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  [textureView1 addSubview:textureView1ContentView];
  [textureView1ContentView release];
  [contentView addSubview:textureView1];
  textureView1.alpha = 1.0;
  textureView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textureView1.backgroundColor = [UIColor colorWithRed:0.6 green:0.6 blue:0.6 alpha:1.0];
  textureView1.layer.cornerRadius = 0.0;
  textureView1.layer.borderWidth = 0.0;
  textureView1.layer.borderColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowOpacity = 0.0;
  textureView1.layer.shadowRadius = 3.0;
  textureView1ContentView.layer.cornerRadius = 0.0;
  textureView1.layer.shadowOffset = CGSizeMake(0, -3);
  [textureView1 release];
  
  
  // ----------------------------;
  // UILabel -> label1;
  // ----------------------------;
  
  UILabel *label1 = [[UILabel alloc] initWithFrame:CGRectMake(20, 60, 200, 24)];
  [textureView1ContentView addSubview:label1];
  label1.alpha = 1.0;
  label1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label1.text = @"Equipment Name:";
  label1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label1.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label1.textAlignment = UITextAlignmentLeft;
  label1.shadowOffset = CGSizeMake(0, -1);
  label1.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label1 release];
  
  
  // ----------------------------;
  // UILabel -> label2;
  // ----------------------------;
  
  UILabel *label2 = [[UILabel alloc] initWithFrame:CGRectMake(20, 100, 200, 24)];
  [textureView1ContentView addSubview:label2];
  label2.alpha = 1.0;
  label2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label2.text = @"Equipment Location:";
  label2.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label2.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label2.textAlignment = UITextAlignmentLeft;
  label2.shadowOffset = CGSizeMake(0, -1);
  label2.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label2 release];
  
  
  // ----------------------------;
  // UILabel -> label3;
  // ----------------------------;
  
  UILabel *label3 = [[UILabel alloc] initWithFrame:CGRectMake(20, 140, 200, 24)];
  [textureView1ContentView addSubview:label3];
  label3.alpha = 1.0;
  label3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label3.text = @"Equipment Quantity:";
  label3.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label3.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label3.textAlignment = UITextAlignmentLeft;
  label3.shadowOffset = CGSizeMake(0, -1);
  label3.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label3 release];
  
  
  // ----------------------------;
  // UILabel -> label4;
  // ----------------------------;
  
  UILabel *label4 = [[UILabel alloc] initWithFrame:CGRectMake(20, 180, 200, 24)];
  [textureView1ContentView addSubview:label4];
  label4.alpha = 1.0;
  label4.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label4.text = @"Equipment Advisor:";
  label4.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label4.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label4.textAlignment = UITextAlignmentLeft;
  label4.shadowOffset = CGSizeMake(0, -1);
  label4.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label4 release];
  
  
  // ----------------------------;
  // UILabel -> label5;
  // ----------------------------;
  
  UILabel *label5 = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, 460, 60)];
  [textureView1ContentView addSubview:label5];
  label5.alpha = 1.0;
  label5.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label5.text = @"Flexfuel";
  label5.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label5.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label5.textAlignment = UITextAlignmentCenter;
  label5.shadowOffset = CGSizeMake(0, -1);
  label5.font = [UIFont fontWithName:@"Helvetica" size:28.0];
  [label5 release];
  
  
  // ----------------------------;
  // UILabel -> label6;
  // ----------------------------;
  
  UILabel *label6 = [[UILabel alloc] initWithFrame:CGRectMake(20, 220, 200, 24)];
  [textureView1ContentView addSubview:label6];
  label6.alpha = 1.0;
  label6.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label6.text = @"Arrival Date:";
  label6.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label6.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label6.textAlignment = UITextAlignmentLeft;
  label6.shadowOffset = CGSizeMake(0, -1);
  label6.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label6 release];
  
  
  // ----------------------------;
  // UILabel -> label7;
  // ----------------------------;
  
  UILabel *label7 = [[UILabel alloc] initWithFrame:CGRectMake(20, 260, 200, 24)];
  [textureView1ContentView addSubview:label7];
  label7.alpha = 1.0;
  label7.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label7.text = @"Vendor Contact:";
  label7.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label7.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label7.textAlignment = UITextAlignmentLeft;
  label7.shadowOffset = CGSizeMake(0, -1);
  label7.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label7 release];
  
  
  // ----------------------------;
  // UILabel -> label8;
  // ----------------------------;
  
  UILabel *label8 = [[UILabel alloc] initWithFrame:CGRectMake(20, 300, 200, 24)];
  [textureView1ContentView addSubview:label8];
  label8.alpha = 1.0;
  label8.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label8.text = @"Equipment Cost:";
  label8.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label8.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label8.textAlignment = UITextAlignmentLeft;
  label8.shadowOffset = CGSizeMake(0, -1);
  label8.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label8 release];
  
  
  // ----------------------------;
  // UILabel -> label9;
  // ----------------------------;
  
  UILabel *label9 = [[UILabel alloc] initWithFrame:CGRectMake(20, 340, 200, 24)];
  [textureView1ContentView addSubview:label9];
  label9.alpha = 1.0;
  label9.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label9.text = @"Support Cost:";
  label9.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label9.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label9.textAlignment = UITextAlignmentLeft;
  label9.shadowOffset = CGSizeMake(0, -1);
  label9.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label9 release];
  
  
  // ----------------------------;
  // UILabel -> label10;
  // ----------------------------;
  
  UILabel *label10 = [[UILabel alloc] initWithFrame:CGRectMake(20, 380, 200, 24)];
  [textureView1ContentView addSubview:label10];
  label10.alpha = 1.0;
  label10.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label10.text = @"Unit Point of Contact:";
  label10.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label10.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label10.textAlignment = UITextAlignmentLeft;
  label10.shadowOffset = CGSizeMake(0, -1);
  label10.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label10 release];
  
  
  // ----------------------------;
  // UITextField -> textField1;
  // ----------------------------;
  
  UITextField *textField1 = [[UITextField alloc] initWithFrame:CGRectMake(220, 60, 260, 30)];
  [textureView1ContentView addSubview:textField1];
  textField1.alpha = 1.0;
  textField1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField1.text = @"Flexfuel 2.0";
  textField1.borderStyle = UITextBorderStyleRoundedRect;
  textField1.textAlignment = UITextAlignmentLeft;
  textField1.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField1.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField1 release];
  
  
  // ----------------------------;
  // UITextField -> textField2;
  // ----------------------------;
  
  UITextField *textField2 = [[UITextField alloc] initWithFrame:CGRectMake(220, 220, 260, 30)];
  [textureView1ContentView addSubview:textField2];
  textField2.alpha = 1.0;
  textField2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField2.text = @"18 April 2013";
  textField2.borderStyle = UITextBorderStyleRoundedRect;
  textField2.textAlignment = UITextAlignmentLeft;
  textField2.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField2.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField2.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField2 release];
  
  
  // ----------------------------;
  // UITextField -> textField3;
  // ----------------------------;
  
  UITextField *textField3 = [[UITextField alloc] initWithFrame:CGRectMake(220, 260, 260, 30)];
  [textureView1ContentView addSubview:textField3];
  textField3.alpha = 1.0;
  textField3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField3.text = @"John.doe@flexfuel.com";
  textField3.borderStyle = UITextBorderStyleRoundedRect;
  textField3.textAlignment = UITextAlignmentLeft;
  textField3.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField3.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField3.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField3 release];
  
  
  // ----------------------------;
  // UITextField -> textField4;
  // ----------------------------;
  
  UITextField *textField4 = [[UITextField alloc] initWithFrame:CGRectMake(220, 340, 260, 30)];
  [textureView1ContentView addSubview:textField4];
  textField4.alpha = 1.0;
  textField4.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField4.text = @"$40,500";
  textField4.borderStyle = UITextBorderStyleRoundedRect;
  textField4.textAlignment = UITextAlignmentLeft;
  textField4.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField4.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField4.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField4 release];
  
  
  // ----------------------------;
  // UITextField -> textField5;
  // ----------------------------;
  
  UITextField *textField5 = [[UITextField alloc] initWithFrame:CGRectMake(220, 300, 260, 30)];
  [textureView1ContentView addSubview:textField5];
  textField5.alpha = 1.0;
  textField5.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField5.text = @"$425,000";
  textField5.borderStyle = UITextBorderStyleRoundedRect;
  textField5.textAlignment = UITextAlignmentLeft;
  textField5.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField5.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField5.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField5 release];
  
  
  // ----------------------------;
  // UITextField -> textField6;
  // ----------------------------;
  
  UITextField *textField6 = [[UITextField alloc] initWithFrame:CGRectMake(220, 380, 260, 30)];
  [textureView1ContentView addSubview:textField6];
  textField6.alpha = 1.0;
  textField6.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField6.text = @"CPT Jones";
  textField6.borderStyle = UITextBorderStyleRoundedRect;
  textField6.textAlignment = UITextAlignmentLeft;
  textField6.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField6.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField6.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField6 release];
  
  
  // ----------------------------;
  // UITextField -> textField7;
  // ----------------------------;
  
  UITextField *textField7 = [[UITextField alloc] initWithFrame:CGRectMake(220, 140, 260, 30)];
  [textureView1ContentView addSubview:textField7];
  textField7.alpha = 1.0;
  textField7.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField7.text = @"8";
  textField7.borderStyle = UITextBorderStyleRoundedRect;
  textField7.textAlignment = UITextAlignmentLeft;
  textField7.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField7.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField7.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField7 release];
  
  
  // ----------------------------;
  // UILabel -> label11;
  // ----------------------------;
  
  UILabel *label11 = [[UILabel alloc] initWithFrame:CGRectMake(20, 420, 200, 24)];
  [textureView1ContentView addSubview:label11];
  label11.alpha = 1.0;
  label11.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label11.text = @"Unit Phone Number:";
  label11.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label11.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label11.textAlignment = UITextAlignmentLeft;
  label11.shadowOffset = CGSizeMake(0, -1);
  label11.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label11 release];
  
  
  // ----------------------------;
  // UITextField -> textField8;
  // ----------------------------;
  
  UITextField *textField8 = [[UITextField alloc] initWithFrame:CGRectMake(220, 180, 260, 30)];
  [textureView1ContentView addSubview:textField8];
  textField8.alpha = 1.0;
  textField8.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField8.text = @"Joe Amadee";
  textField8.borderStyle = UITextBorderStyleRoundedRect;
  textField8.textAlignment = UITextAlignmentLeft;
  textField8.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField8.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField8.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField8 release];
  
  
  // ----------------------------;
  // UITextField -> textField9;
  // ----------------------------;
  
  UITextField *textField9 = [[UITextField alloc] initWithFrame:CGRectMake(220, 420, 260, 30)];
  [textureView1ContentView addSubview:textField9];
  textField9.alpha = 1.0;
  textField9.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField9.text = @"703-704-4328";
  textField9.borderStyle = UITextBorderStyleRoundedRect;
  textField9.textAlignment = UITextAlignmentLeft;
  textField9.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField9.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField9.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField9 release];
  
  
  // ----------------------------;
  // UITextField -> textField10;
  // ----------------------------;
  
  UITextField *textField10 = [[UITextField alloc] initWithFrame:CGRectMake(220, 100, 260, 30)];
  [textureView1ContentView addSubview:textField10];
  textField10.alpha = 1.0;
  textField10.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField10.text = @"Dakar, Senegal";
  textField10.borderStyle = UITextBorderStyleRoundedRect;
  textField10.textAlignment = UITextAlignmentLeft;
  textField10.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField10.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField10.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField10 release];
  
  
  // ----------------------------;
  // UILabel -> label12;
  // ----------------------------;
  
  UILabel *label12 = [[UILabel alloc] initWithFrame:CGRectMake(20, 460, 200, 24)];
  [textureView1ContentView addSubview:label12];
  label12.alpha = 1.0;
  label12.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label12.text = @"Unit Email Address:";
  label12.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label12.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label12.textAlignment = UITextAlignmentLeft;
  label12.shadowOffset = CGSizeMake(0, -1);
  label12.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label12 release];
  
  
  // ----------------------------;
  // UITextField -> textField11;
  // ----------------------------;
  
  UITextField *textField11 = [[UITextField alloc] initWithFrame:CGRectMake(220, 460, 260, 30)];
  [textureView1ContentView addSubview:textField11];
  textField11.alpha = 1.0;
  textField11.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField11.text = @"Steve.jones@mail.mil";
  textField11.borderStyle = UITextBorderStyleRoundedRect;
  textField11.textAlignment = UITextAlignmentLeft;
  textField11.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField11.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField11.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField11 release];
  
  
  contentView.frame = self.view.bounds;
  [self.view addSubview:contentView];
  [contentView release];
}

- (void)viewDidUnload {
  [super viewDidUnload];
}

- (void)dealloc {
  [super dealloc];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleBlackOpaque animated:animated];
}


// ----------------
// Navigation Bar
// ----------------

- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
  return NO;
}


// ----------------
// Action
// ----------------

- (void)didTap_barButton1:(id)sender forEvent:(UIEvent *)event {
  [self dismissModalViewControllerAnimated:YES];
}




@end