//
//  HomeScreenLocationsViewViewControllerRight.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "HomeScreenLocationsViewViewControllerRight.h"

#import "GradientView.h"
#import "MKMapView+ZoomLevel.h"

@implementation HomeScreenLocationsViewViewControllerRight


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return UIInterfaceOrientationIsLandscape(toInterfaceOrientation);
}


- (void)viewDidLoad {
  [super viewDidLoad];
  
  // ----------------------------;
  // View Controller Root View;
  // ----------------------------;
  
  UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 703, 748)];
  contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  contentView.backgroundColor = [UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0];
  
  // ----------------------------;
  // UINavigationBar -> navigationBar1;
  // ----------------------------;
  
  UINavigationBar *navigationBar1 = [[UINavigationBar alloc] initWithFrame:CGRectMake(0, 0, 703, 44)];
  navigationBar1.delegate = (id<UINavigationBarDelegate>)self;
  UINavigationItem *navigationBar1BackItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  UINavigationItem *navigationBar1TopItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  NSArray *navigationBar1Items = [NSArray arrayWithObjects:navigationBar1BackItem, navigationBar1TopItem, nil];
  [navigationBar1 setItems:navigationBar1Items animated:NO];
  [contentView addSubview:navigationBar1];
  navigationBar1.alpha = 1.0;
  navigationBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
  navigationBar1.barStyle = UIBarStyleDefault;
  navigationBar1.tintColor = [UIColor colorWithRed:0.2 green:0.2 blue:0.2 alpha:1.0];
  navigationBar1.topItem.title = @"Equipment Detail";
  [navigationBar1 setTitleVerticalPositionAdjustment:0.0 forBarMetrics:UIBarMetricsDefault];
  navigationBar1.topItem.hidesBackButton = YES;
  
  // ----------------------------;
  // Navigation Bar Right Button -> barButton1;
  // ----------------------------;
  
  UIBarButtonItem *barButton1 = [[[UIBarButtonItem alloc] initWithTitle:@"Save" style:UIBarButtonItemStyleBordered target:nil action:nil] autorelease];
  [barButton1 setTintColor:[UIColor colorWithRed:0.4 green:0.4 blue:0.4 alpha:1.0]];
  barButton1.target = self;
  barButton1.action = @selector(didTap_barButton1:forEvent:);
  
  navigationBar1.topItem.rightBarButtonItem = barButton1;
  [navigationBar1 release];
  
  
  // ----------------------------;
  // MKMapView -> mapView1;
  // ----------------------------;
  
  MKMapView *mapView1 = [[MKMapView alloc] initWithFrame:CGRectMake(0, 44, 703, 450)];
  [contentView addSubview:mapView1];
  mapView1.alpha = 1.0;
  mapView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  mapView1.mapType = MKMapTypeHybrid;
  [mapView1 setCenterCoordinate:CLLocationCoordinate2DMake(18.070000000000007, -15.970000000000006) zoomLevel:6 animated:NO];
  [mapView1 release];
  
  
  // ----------------------------;
  // UILabel -> label1;
  // ----------------------------;
  
  UILabel *label1 = [[UILabel alloc] initWithFrame:CGRectMake(20, 510, 200, 20)];
  [contentView addSubview:label1];
  label1.alpha = 1.0;
  label1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label1.text = @"Equipment Name";
  label1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label1.backgroundColor = [UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0];
  label1.textAlignment = UITextAlignmentCenter;
  label1.shadowOffset = CGSizeMake(0, -1);
  label1.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label1 release];
  
  
  // ----------------------------;
  // UILabel -> label2;
  // ----------------------------;
  
  UILabel *label2 = [[UILabel alloc] initWithFrame:CGRectMake(252, 510, 200, 20)];
  [contentView addSubview:label2];
  label2.alpha = 1.0;
  label2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label2.text = @"Quantity";
  label2.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label2.backgroundColor = [UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0];
  label2.textAlignment = UITextAlignmentCenter;
  label2.shadowOffset = CGSizeMake(0, -1);
  label2.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label2 release];
  
  
  // ----------------------------;
  // UILabel -> label3;
  // ----------------------------;
  
  UILabel *label3 = [[UILabel alloc] initWithFrame:CGRectMake(484, 510, 200, 20)];
  [contentView addSubview:label3];
  label3.alpha = 1.0;
  label3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label3.text = @"Equipment Advisor";
  label3.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label3.backgroundColor = [UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0];
  label3.textAlignment = UITextAlignmentCenter;
  label3.shadowOffset = CGSizeMake(0, -1);
  label3.font = [UIFont fontWithName:@"Helvetica" size:20.0];
  [label3 release];
  
  
  // ----------------------------;
  // UITextField -> textField1;
  // ----------------------------;
  
  UITextField *textField1 = [[UITextField alloc] initWithFrame:CGRectMake(20, 545, 200, 30)];
  [contentView addSubview:textField1];
  textField1.alpha = 1.0;
  textField1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField1.text = @"Sun Dial";
  textField1.borderStyle = UITextBorderStyleRoundedRect;
  textField1.textAlignment = UITextAlignmentLeft;
  textField1.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField1.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField1 release];
  
  
  // ----------------------------;
  // UITextField -> textField2;
  // ----------------------------;
  
  UITextField *textField2 = [[UITextField alloc] initWithFrame:CGRectMake(252, 545, 200, 30)];
  [contentView addSubview:textField2];
  textField2.alpha = 1.0;
  textField2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField2.text = @"2";
  textField2.borderStyle = UITextBorderStyleRoundedRect;
  textField2.textAlignment = UITextAlignmentLeft;
  textField2.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField2.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField2.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField2 release];
  
  
  // ----------------------------;
  // UITextField -> textField3;
  // ----------------------------;
  
  UITextField *textField3 = [[UITextField alloc] initWithFrame:CGRectMake(20, 592, 200, 30)];
  [contentView addSubview:textField3];
  textField3.alpha = 1.0;
  textField3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField3.text = @"1 kW Flexfuel";
  textField3.borderStyle = UITextBorderStyleRoundedRect;
  textField3.textAlignment = UITextAlignmentLeft;
  textField3.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField3.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField3.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField3 release];
  
  
  // ----------------------------;
  // UITextField -> textField4;
  // ----------------------------;
  
  UITextField *textField4 = [[UITextField alloc] initWithFrame:CGRectMake(252, 592, 200, 30)];
  [contentView addSubview:textField4];
  textField4.alpha = 1.0;
  textField4.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField4.text = @"6";
  textField4.borderStyle = UITextBorderStyleRoundedRect;
  textField4.textAlignment = UITextAlignmentLeft;
  textField4.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField4.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField4.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField4 release];
  
  
  // ----------------------------;
  // UITextField -> textField5;
  // ----------------------------;
  
  UITextField *textField5 = [[UITextField alloc] initWithFrame:CGRectMake(484, 545, 200, 30)];
  [contentView addSubview:textField5];
  textField5.alpha = 1.0;
  textField5.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField5.text = @"Mike Sargent";
  textField5.borderStyle = UITextBorderStyleRoundedRect;
  textField5.textAlignment = UITextAlignmentLeft;
  textField5.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField5.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField5.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField5 release];
  
  
  // ----------------------------;
  // UITextField -> textField6;
  // ----------------------------;
  
  UITextField *textField6 = [[UITextField alloc] initWithFrame:CGRectMake(484, 592, 200, 30)];
  [contentView addSubview:textField6];
  textField6.alpha = 1.0;
  textField6.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField6.text = @"Mike Sargent";
  textField6.borderStyle = UITextBorderStyleRoundedRect;
  textField6.textAlignment = UITextAlignmentLeft;
  textField6.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField6.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField6.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField6 release];
  
  
  // ----------------------------;
  // UITextField -> textField7;
  // ----------------------------;
  
  UITextField *textField7 = [[UITextField alloc] initWithFrame:CGRectMake(20, 639, 200, 30)];
  [contentView addSubview:textField7];
  textField7.alpha = 1.0;
  textField7.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField7.text = @"Solar Stik";
  textField7.borderStyle = UITextBorderStyleRoundedRect;
  textField7.textAlignment = UITextAlignmentLeft;
  textField7.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField7.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField7.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField7 release];
  
  
  // ----------------------------;
  // UITextField -> textField8;
  // ----------------------------;
  
  UITextField *textField8 = [[UITextField alloc] initWithFrame:CGRectMake(252, 639, 200, 30)];
  [contentView addSubview:textField8];
  textField8.alpha = 1.0;
  textField8.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField8.text = @"4";
  textField8.borderStyle = UITextBorderStyleRoundedRect;
  textField8.textAlignment = UITextAlignmentLeft;
  textField8.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField8.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField8.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField8 release];
  
  
  // ----------------------------;
  // UITextField -> textField9;
  // ----------------------------;
  
  UITextField *textField9 = [[UITextField alloc] initWithFrame:CGRectMake(484, 639, 200, 30)];
  [contentView addSubview:textField9];
  textField9.alpha = 1.0;
  textField9.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField9.text = @"Jed Deplitch";
  textField9.borderStyle = UITextBorderStyleRoundedRect;
  textField9.textAlignment = UITextAlignmentLeft;
  textField9.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField9.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField9.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField9 release];
  
  
  // ----------------------------;
  // UITextField -> textField10;
  // ----------------------------;
  
  UITextField *textField10 = [[UITextField alloc] initWithFrame:CGRectMake(20, 688, 200, 30)];
  [contentView addSubview:textField10];
  textField10.alpha = 1.0;
  textField10.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField10.text = @"";
  textField10.borderStyle = UITextBorderStyleRoundedRect;
  textField10.textAlignment = UITextAlignmentLeft;
  textField10.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField10.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField10.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField10 release];
  
  
  // ----------------------------;
  // UITextField -> textField11;
  // ----------------------------;
  
  UITextField *textField11 = [[UITextField alloc] initWithFrame:CGRectMake(252, 688, 200, 30)];
  [contentView addSubview:textField11];
  textField11.alpha = 1.0;
  textField11.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField11.borderStyle = UITextBorderStyleRoundedRect;
  textField11.textAlignment = UITextAlignmentLeft;
  textField11.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField11.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField11.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField11 release];
  
  
  // ----------------------------;
  // UITextField -> textField12;
  // ----------------------------;
  
  UITextField *textField12 = [[UITextField alloc] initWithFrame:CGRectMake(484, 688, 200, 30)];
  [contentView addSubview:textField12];
  textField12.alpha = 1.0;
  textField12.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textField12.borderStyle = UITextBorderStyleRoundedRect;
  textField12.textAlignment = UITextAlignmentLeft;
  textField12.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
  textField12.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  textField12.font = [UIFont fontWithName:@"Helvetica" size:17.0];
  [textField12 release];
  
  
  contentView.frame = self.view.bounds;
  [self.view addSubview:contentView];
  [contentView release];
}

- (void)viewDidUnload {
  [super viewDidUnload];
}

- (void)dealloc {
  [super dealloc];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleBlackOpaque animated:animated];
}


// ----------------
// Navigation Bar
// ----------------

- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
  return NO;
}


// ----------------
// Action
// ----------------

- (void)didTap_barButton1:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Equipment Detail Saved";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"Close"];
  [alertView show];
  [alertView release];
}




@end